name: PR Preview

# Si attiva quando una PR viene aperta/aggiornata verso dev
on:
    pull_request:
        branches:
            - 'dev'
        types:
            - opened
            - synchronize
            - reopened

jobs:
    publish_preview:
        name: Publish PR Preview
        type: update
        params:
            branch: pr-${{ github.event.pull_request.number }}

    comment_on_pr:
        name: Comment QR Code on PR
        needs: [publish_preview]
        type: github-comment
