name: Preview Update on Feature Branch

# Triggers on every push to features/* or feature/* branches
on:
    push:
        branches:
            - 'features/**'
            - 'feature/**'

jobs:
    publish_update:
        name: Publish Preview Update
        type: update
        params:
            branch: ${{ github.ref_name }}
