name: Release Update

# Triggers when a version tag is pushed (created by npm run release)
on:
    push:
        tags:
            - 'v*'

jobs:
    publish_release:
        name: Publish Release to Preview Channel
        type: update
        params:
            channel: preview
            message: 'Release ${{ github.ref_name }}'
