name: EAS Build & Submit
on:
  push:
    branches:
      - master
      - dev
      - features/eas-workflow

permissions:
  contents: write

jobs:
  build:
    name: Install and Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: npm

      - name: Setup Git User
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          token: ${{ secrets.EXPO_TOKEN }}
          eas-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Release Version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ "${{ github.ref_name }}" == "master" ]]; then
            npm run release -- --ci
          else
            npm run release -- --ci --prerelease=dev
          fi

      - name: Create Service Account JSON
        env:
          GOOGLE_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
        run: echo "$GOOGLE_SERVICE_ACCOUNT" > google-services-key.json

      - name: Build Android App Bundle
        run: eas build --platform android --profile production --non-interactive --local

      - name: Submit to Google Play
        run: eas submit --platform android --profile production --latest --non-interactive
